# Generated by Django 5.2.3 on 2026-01-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_order_address_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sts',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
