# Generated by Django 5.2.3 on 2026-01-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
    ]
