# Generated by Django 5.2.3 on 2026-02-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='banners')),
                ('is_veg', models.BooleanField(default=True, help_text='Checked for Veg, Unchecked for Non-Veg')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
