# Generated by Django 5.2.3 on 2026-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sts',
            field=models.CharField(choices=[('waiting for accept', 'waiting for accept'), ('accepted and cooking', 'accepted and cooking'), ('ready to pickup', 'ready to pickup'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='waiting for accept', max_length=20),
        ),
    ]
