# Generated by Django 5.2.3 on 2026-02-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_order_order_sts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='COD', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sts',
            field=models.CharField(choices=[('waiting for accept', 'waiting for accept'), ('accepted and cooking', 'accepted and cooking'), ('ready to pickup', 'ready to pickup'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='waiting for accept', max_length=50),
        ),
    ]
